name: Makefile CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Move to src
      run: cd src/audio_extract
    
    - name: Install dependencies
      run: make install
      
    - name: Test code
      run: make test


    
